### ISSUE TITLE
使用手机访问时，页面底部显示一行不应该存在的文本

### ISSUE THREAD

**Issue by BlacK201** [nexmoe/typecho-theme-nexmoe#1]
原因应该是出在这一行，不知道直接删除会不会带来什么问题。。
https://github.com/nexmoe/typecho-theme-nexmoe/blob/98e0e368eb99825eec1c022a61584aa4822d8e09/layout/_partial/after-footer.php#L3

**Comment by nexmoe** [comment]
删除没影响，是移植遗留的问题
